# Generated by Django 4.2.3 on 2023-07-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_comment_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='starttime',
        ),
    ]
