# Generated by Django 4.2.3 on 2023-07-16 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_current_bid_alter_listing_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 23, 57, 47, 367687)),
        ),
    ]
